sudo: false
language: scala
scala:
  - 2.13.1
jdk:
  - oraclejdk8
script:
  - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers