name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-sbt-libs
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.cache/coursier/v1
        key: build-${{ env.cache-name }}-${{ hashFiles('build.sbt') }}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build executable
      run: sbt package
    - name: Run Test
      run: sbt clean coverage test
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Send Coverage Report
      run: sbt coverageReport
      path-to-lcov: "./target/scala-2.13/coverage-report/cobertura.xml"
